ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "visibleInStore" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "customerPhone" TEXT;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "deliveryMethod" TEXT;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "deliveryAddress" JSONB;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "observations" TEXT;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP(3);

ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "costPrice" DECIMAL(10,2) NOT NULL DEFAULT 0.00;
